# Generated by Django 4.0.6 on 2022-07-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('date_of_birth', models.DateField(max_length=8)),
                ('adress', models.CharField(max_length=128)),
                ('tel_num', models.IntegerField(max_length=13)),
            ],
        ),
    ]
